services:
  whatsapp-api:
    build: .
    container_name: whatsapp-api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - NODE_OPTIONS=--max-old-space-size=256 --expose-gc
    volumes:
      # Volumen para persistir la sesión de WhatsApp
      - whatsapp-session:/app/.wwebjs_auth
      - whatsapp-cache:/app/.wwebjs_cache
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 512M
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  whatsapp-session:
    driver: local
  whatsapp-cache:
    driver: local
